name: snippet
version: '0.1'
summary: Snippet app for programers
description: |
  This app is to store snippet code for programers.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  desktop:
    command: env LC_ALL=C desktop-launch $SNAP/Snippet
    desktop: Snippet.desktop
  snippet:
    command: env LC_ALL=C desktop-launch $SNAP/Snippet
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl

parts:
  snippet:
    plugin: dump
    source: ../release-builds/Snippet-linux-x64
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    after:
      - desktop-glib-only
